### ISSUE TITLE
Enabling translations

### ISSUE THREAD

**Issue by vkaracic** [edx-solutions/xblock-drag-and-drop-v2#120]
Hello!
I'm trying to enable translations for this xblock but I can't seem to do it successfully. I've compiled the eo language .po file to the .mo file and enabled eo language in studio with ``?preview-lang=eo``, everything changed to Esperanto but not the text in the edit modal of this xblock.
How can I enable the translations?

**Comment by e-kolpakov** [comment]
@vkaracic Hi! Sorry for not responding earlier - probably no one actually monitors "our" repos for new issues regularly (personally I've got too many notifications for other stuff, so I tend to ignore Github notifications completely, unless explicitly tagged)..

Regarding the question - there are some limitations in Xblock translations and I'm not quite sure if they are fixed or not. But last time I checked (half a year ago) it was broken - [see the i18n compatibility section](https://github.com/edx-solutions/xblock-drag-and-drop-v2#i18n-compatibility) note. Copying it here:

> Note: As of 2016-08-04, XBlock translation feature was (partially?) broken, so switching to other locale did not cause Drag and Drop v2 to be fully translated - only some strings that happen to exist in edx-platform translation files are translated. There's an ongoing effort to fix this problem: https://openedx.atlassian.net/browse/WL-230.

As far as I can tell WL-230 is marked as fixed, so it should work now, but since you're facing problems there might be some missing pieces. I vaguely recall someone (probably @ziafazal) worked on translations in some other (or this one?) block and reported everything worked for him. @ziafazal can you confirm was that you and if it worked for you?

**Comment by e-kolpakov** [comment]
@vkaracic Also, if it works now it would be great if you could update the readme with instructions on how to properly enable it.

**Comment by ziafazal** [comment]
@vkaracic @e-kolpakov Last time when I was adding translations to different xblocks it expreinced the same limitation which is only those strings which are marked for translations using [ModuleI18nService](https://github.com/edx/edx-platform/blob/955dc69e704b143601b492cf6d09d5fca5c4d361/common/lib/xmodule/xmodule/modulestore/django.py#L359) are translated.

**Comment by vkaracic** [comment]
@e-kolpakov it still doesn't seem to be working:
![screenshot from 2017-03-21 12-32-27](https://cloud.githubusercontent.com/assets/2808092/24145674/85f1d5e8-0e32-11e7-866b-df903cdaaace.png)

@ziafazal can you show me the places where you used that service successfully? Maybe I can imitate it.

**Comment by vkaracic** [comment]
@ziafazal pretty please? :)

**Comment by ziafazal** [comment]
@vkaracic see the string on the top of the popup.

**Comment by vkaracic** [comment]
@ziafazal I see, but I also found the strings in the popup in EO language .po file but that doesn't get translated.

**Comment by ziafazal** [comment]
@vkaracic see my comment above only those strings marked for translations using ModuleI18nService are translated. If we have some translations in .po but those strings are not marked for translations using ModuleI18nService then those would not get translated.
